apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-rollout
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/crazylearning-cr/argo-rollout-guestbook-canary.git
    path: guestbook-rollout
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true          # delete resources removed from Git
      selfHeal: true       # revert out-of-band changes
    syncOptions:
      - CreateNamespace=true   # if you deploy to non-existing ns in future
